# MSFW Configuration
# 
# Environment Variable Interpolation:
# Use ${VAR_NAME} for required environment variables
# Use ${VAR_NAME:default_value} for optional environment variables with defaults
#
# Examples:
# secret_key = "${SECRET_KEY}"                           # Required env var
# database_url = "${DATABASE_URL:sqlite+aiosqlite:///./app.db}"  # With default
# debug = "${DEBUG:false}"                              # Boolean with default

# Application settings
app_name = "${APP_NAME:Test Project Application}"
description = "A test project for MSFW framework"
version = "1.0.0"
debug = "${DEBUG:false}"
host = "${HOST:0.0.0.0}"
port = "${PORT:8000}"

# Database settings
[database]
url = "${DATABASE_URL:sqlite+aiosqlite:///./test_project.db}"
echo = "${DATABASE_ECHO:false}"
pool_size = "${DATABASE_POOL_SIZE:5}"

# Security settings
[security]
secret_key = "${SECRET_KEY:dev-secret-key-change-in-production}"
algorithm = "HS256"
access_token_expire_minutes = "${ACCESS_TOKEN_EXPIRE:30}"

# Redis settings (if needed)
[redis]
url = "${REDIS_URL:redis://localhost:6379/0}"

# Logging settings
[logging]
level = "${LOG_LEVEL:INFO}"
format = "${LOG_FORMAT:text}"

# CORS settings
[cors]
allow_origins = ["${CORS_ORIGINS:*}"]
allow_credentials = true

# Monitoring settings
[monitoring]
enabled = "${MONITORING_ENABLED:true}"
prometheus_enabled = "${PROMETHEUS_ENABLED:true}"
metrics_path = "/metrics"
health_check_path = "/health" 